# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPHPTravels():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pHPTravels(self):
    self.driver.get("https://phptravels.net/")
    self.driver.set_window_size(1453, 865)
    self.driver.find_element(By.NAME, "from").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) .d-inline-block").click()
    self.driver.find_element(By.NAME, "to").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) strong > small").click()
    self.driver.find_element(By.ID, "departure").click()
    self.driver.find_element(By.CSS_SELECTOR, ".datepicker:nth-child(20) .new:nth-child(6)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#flights-search > .c8LPF-icon > path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#flights-search > .c8LPF-icon > path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".searches > .h6")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".searches > .h6").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3 .dropdown-item").click()
    self.driver.find_element(By.LINK_TEXT, "Hotels").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-4:nth-child(1) > .rounded-3 .w-100").click()
    self.driver.find_element(By.ID, "adults").click()
    dropdown = self.driver.find_element(By.ID, "adults")
    dropdown.find_element(By.XPATH, "//option[. = '6']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#adults > option:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ladda").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".rounded:nth-child(1) td > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded:nth-child(1) td > .btn").click()
    self.driver.find_element(By.ID, "p-first-name").click()
    self.driver.find_element(By.ID, "p-first-name").send_keys("Anjana")
    self.driver.find_element(By.ID, "agreechb").click()
    element = self.driver.find_element(By.ID, "booking")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "booking").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
